language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
before_install: cd client
script: npm run build
skip_cleanup: true
deploy:
  provider: surge
  project: ./client/build/
  domain: sf-movie-quiz.surge.sh
